# this project uses stylelint for linting, but some editors/tools still need a
# sass-lint configuration, so here is a similar ruleset

rules:
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  mixins-before-declarations: 0
  no-qualifying-elements: 0
  nesting-depth:
    - 1
    - max-depth: 4
  indentation: 2
  no-important: 2
  leading-zero:
    - 2
    - include: true
