rules:
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  mixins-before-declarations: 0
  no-qualifying-elements: 0
  nesting-depth:
    - 1
    - max-depth: 4
  indentation: 2
  no-important: 2
